name: pytorch_clean_back
channels:
  - conda-forge
  - metric-learning
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cuda-version=12.8
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.3.0
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2021.4.0
  - joblib=1.4.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.13.0.11
  - libcurand=10.3.9.55
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.22
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - packaging=23.2
  - pillow=10.4.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.8.13
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - pytorch-metric-learning=1.6.3
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.32.3
  - scipy=1.9.3
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchaudio=0.13.0
  - torchmetrics=0.11.4
  - torchvision=0.14.0
  - tqdm=4.64.1
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - absl-py==2.1.0
    - aenum==3.1.15
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - async-timeout==5.0.1
    - attrs==25.1.0
    - beautifulsoup4==4.13.4
    - bleach==6.1.0
    - cachetools==5.5.2
    - click==8.1.8
    - contourpy==1.1.1
    - cssselect==1.2.0
    - cssutils==2.11.1
    - cycler==0.12.1
    - dataframe-image==0.2.7
    - defusedxml==0.7.1
    - dicom2nifti==2.4.8
    - docker-pycreds==0.4.0
    - eval-type-backport==0.2.2
    - fastjsonschema==2.21.1
    - filelock==3.16.1
    - fonttools==4.56.0
    - frozenlist==1.5.0
    - fsspec==2025.2.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - google-auth==2.38.0
    - google-auth-oauthlib==0.4.6
    - greenlet==3.1.1
    - grpcio==1.70.0
    - hydra-core==1.3.2
    - imageio==2.35.1
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - jinja2==3.1.5
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyterlab-pygments==0.3.0
    - kiwisolver==1.4.7
    - lightly==1.5.0
    - lightly-utils==0.0.2
    - lightning-utilities==0.11.9
    - lxml==5.4.0
    - markdown==3.7
    - markupsafe==2.1.5
    - matplotlib==3.6.2
    - medpy==0.4.0
    - mistune==3.1.3
    - monai==1.0.1
    - more-itertools==10.5.0
    - mpmath==1.3.0
    - multidict==6.1.0
    - nbclient==0.10.1
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - networkx==3.1
    - nibabel==4.0.2
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.8.61
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - pandas==1.5.2
    - pandocfilters==1.5.1
    - pathtools==0.1.2
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - playwright==1.48.0
    - propcache==0.2.0
    - protobuf==3.20.3
    - psutil==7.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pydantic==1.10.9
    - pydantic-core==2.27.2
    - pydicom==2.4.4
    - pyee==12.0.0
    - pygments==2.19.1
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - python-gdcm==3.0.24.1
    - pytorch-lightning==2.4.0
    - pytz==2025.1
    - pywavelets==1.4.1
    - pyyaml==6.0.2
    - pyzmq==26.4.0
    - referencing==0.35.1
    - requests-oauthlib==2.0.0
    - rpds-py==0.20.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - sentry-sdk==2.22.0
    - setproctitle==1.3.4
    - simpleitk==2.2.1
    - smmap==5.0.2
    - soupsieve==2.7
    - sympy==1.13.3
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tifffile==2023.7.10
    - tinycss2==1.2.1
    - torch==2.4.1
    - tornado==6.4.2
    - traitlets==5.14.3
    - triton==3.0.0
    - typing-extensions==4.12.2
    - wandb==0.15.3
    - webencodings==0.5.1
    - werkzeug==3.0.6
    - yarl==1.15.2
    - zipp==3.20.2
